// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/getting-started.zh-CN":{"path":"getting-started","id":"docs/getting-started.zh-CN","parentId":"DocLayout"},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"docs/index.zh-CN":{"path":"","id":"docs/index.zh-CN","parentId":"DocLayout"},"docs/help.zh-CN":{"path":"help","id":"docs/help.zh-CN","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/help":{"path":"help","id":"docs/help","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@22.13.14_eslint@8.57.1_l_e7748234c7c4b132be9e44d0e471201d/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@22.13.14_eslint@8.57.1_l_e7748234c7c4b132be9e44d0e471201d/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/getting-started.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.zh-CN.md" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.zh-CN.md')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.md')),
'docs/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__index.zh-CN.md" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.zh-CN.md')),
'docs/help.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__help.zh-CN.md" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.zh-CN.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.md')),
'docs/help': React.lazy(() => import(/* webpackChunkName: "docs__help.md" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@22.13.14_eslint@8.57.1_l_e7748234c7c4b132be9e44d0e471201d/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
