// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@22.13.14_eslint@8.57.1_l_e7748234c7c4b132be9e44d0e471201d/node_modules/dumi/theme-default/slots/SearchResult/index.js';
