// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.zh-CN.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.zh-CN.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.zh-CN.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.zh-CN.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.zh-CN.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.zh-CN.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.md?type=demo-index';

export const filesMeta = {
  'docs/getting-started.zh-CN': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.zh-CN.md?type=text'),
  },
  'docs/getting-started': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/getting-started.md?type=text'),
  },
  'docs/index.zh-CN': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.zh-CN.md?type=text'),
  },
  'docs/help.zh-CN': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.zh-CN.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/index.md?type=text'),
  },
  'docs/help': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangxiaokun/workBase/personal/frog-hooks/docs/help.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
